version: '3.1'
services:
    next:
        ports:
            - ${PUBLIC_PORT}:${PRIVATE_PORT}
        build:
            context: .
            dockerfile: Dockerfile
            args:
                PRIVATE_PROTOCOL: ${PRIVATE_PROTOCOL}
                PRIVATE_HOSTNAME: ${PRIVATE_HOSTNAME}
                PRIVATE_PORT: ${PRIVATE_PORT}
                PRIVATE_CONTEXT: ${PRIVATE_CONTEXT}
                PUBLIC_PROTOCOL: ${PUBLIC_PROTOCOL}
                PUBLIC_HOSTNAME: ${PUBLIC_HOSTNAME}
                PUBLIC_PORT: ${PUBLIC_PORT}
                PUBLIC_CONTEXT: ${PUBLIC_CONTEXT}
        environment:
            PRIVATE_PROTOCOL: ${PRIVATE_PROTOCOL}
            PRIVATE_HOSTNAME: ${PRIVATE_HOSTNAME}
            PRIVATE_PORT: ${PRIVATE_PORT}
            PRIVATE_CONTEXT: ${PRIVATE_CONTEXT}
            PUBLIC_PROTOCOL: ${PUBLIC_PROTOCOL}
            PUBLIC_HOSTNAME: ${PUBLIC_HOSTNAME}
            PUBLIC_PORT: ${PUBLIC_PORT}
            PUBLIC_CONTEXT: ${PUBLIC_CONTEXT}