swagger: '2.0'
info:
  description: REST API Datos actividad del usuario
  version: 1.0.0-SNAPSHOT
  title: Actividad de un usuario de la aplicación de gestión
host: 'localhost:8080'
basePath: /
tags:
  - name: Activity
    description: Operaciones relacionados con todas las actividades y no con una en específico
  - name: Activity Consult
    description: Operaciones relacionadas con la actividad de consulta del usuario
paths:
  /activities-consults/:
    post:
      tags:
        - Activity Consult
      summary: Crea una actividad de consulta
      description: ' La actividad de consulta se crea a partir de la información recibida'
      operationId: createUsingPOST
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: idCandidate
          in: query
          description: idCandidate
          required: false
          type: string
        - name: idUser
          in: query
          description: idUser
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '201':
          description: CREATED
          schema:
            $ref: '#/definitions/ResponseEntity'
        '400':
          description: BAD_REQUEST
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /activities/:
    get:
      tags:
        - Activity
      summary: Busca la información de todas las actividades en base a una fecha
      description: La fecha tiene que ser formato yyyy-MM-dd
      operationId: findActivityByDateUsingGET
      produces:
        - application/json
      parameters:
        - name: date
          in: query
          description: date
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/activity'
        '204':
          description: NO_CONTENT
          schema:
            type: array
            items:
              $ref: '#/definitions/activity'
        '400':
          description: BAD_REQUEST
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/activities/{id-user}':
    get:
      tags:
        - Activity
      summary: Busca la información de todas las actividades actividad de un usuario
      description: Saca la información en base al identificador de un usuario
      operationId: findActivityByUserUsingGET
      produces:
        - application/json
      parameters:
        - name: id-user
          in: path
          description: id-user
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/activity'
        '204':
          description: NO_CONTENT
          schema:
            type: array
            items:
              $ref: '#/definitions/activity'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /candidates/:
    get:
      tags:
        - Activity
      summary: Busca los identificadores de los candidatos que tiene un usuario relacionado con cualquier tipo de actividad
      description: Saca la información en base a un identificador de usuario
      operationId: findCandidateByUserUsingGET
      produces:
        - application/json
      parameters:
        - name: idUser
          in: query
          description: idUser
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              type: string
        '204':
          description: NOT_CONTENT
          schema:
            type: array
            items:
              type: string
        '400':
          description: BAD_REQUEST
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  ResponseEntity:
    type: object
    properties:
      body:
        type: object
      statusCode:
        type: string
        enum:
          - '100'
          - '101'
          - '102'
          - '103'
          - '200'
          - '201'
          - '202'
          - '203'
          - '204'
          - '205'
          - '206'
          - '207'
          - '208'
          - '226'
          - '300'
          - '301'
          - '302'
          - '303'
          - '304'
          - '305'
          - '307'
          - '308'
          - '400'
          - '401'
          - '402'
          - '403'
          - '404'
          - '405'
          - '406'
          - '407'
          - '408'
          - '409'
          - '410'
          - '411'
          - '412'
          - '413'
          - '414'
          - '415'
          - '416'
          - '417'
          - '418'
          - '419'
          - '420'
          - '421'
          - '422'
          - '423'
          - '424'
          - '426'
          - '428'
          - '429'
          - '431'
          - '451'
          - '500'
          - '501'
          - '502'
          - '503'
          - '504'
          - '505'
          - '506'
          - '507'
          - '508'
          - '509'
          - '510'
          - '511'
      statusCodeValue:
        type: integer
        format: int32
    title: ResponseEntity
  activity:
    type: object
    properties:
      creationDate:
        type: string
        format: date-time
        description: Fecha de creación de la actividad

      id:
        type: integer
        format: int32
        description: Identificador de la actividad

      idCandidate:
        type: string
        description: Identificador del candidato

      idUser:
        type: string
        description: Identificador del usuario de la aplicación

      typeActivity:
        type: string
        description: El tipo de operación de la actividad

    title: activity
    description: 'Una actividad del usuario es un tipo de operación que este puede realizar, '
