swagger: '2.0'
info:
  description: REST API Informaci贸n detallada de la actividad del usuario en la aplicaci贸n
  version: 1.0.0-SNAPSHOT
  title: Informaci贸n detallada de la actividad del usuario en la aplicaci贸n
host: 'localhost:8888'
basePath: /
tags:
  - name: Candidate Citation
    description: Operations related to a candidate of a user
paths:
  '/candidates-citations/':
    get:
      tags:
        - Candidate Citation
      summary: Consult the candidates with whom the user has any summons on a given day.
      description: Take out the information based on a user ID. 
      operationId: getCandidatesByIdUserUsingGET
      produces:
        - application/json
      parameters:
        - name: id-user
          in: query
          description: User Identificator
          required: true
          type: string
        - name: citation-date
          in: query
          description: Date of citation. Has to be yyyy-MM-dd format
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/CandidateCitation'
        '204':
          description: NO_CONTENT
        '400':
          description: BAD_REQUEST
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  CandidateCitation:
    type: object
    properties:
      familyName:
        type: array
        description: Family names of a persona. They arrive ordered.
        items:
          type: string
      givenName:
        type: string
        description: Given name of a person
      idCandidate:
        type: string
        description: Candidate Identifier
      photo:
        type: string
        description: Avatar of a candidate
      preferenceJob:
        type: array
        description: List of all preferences jobs of a candidate. The one with priority 1 is the most preferred by the user.
        items:
          $ref: '#/definitions/PreferenceJobProfile'
      citationDate: 
        type: string
        format: date-time
        description: Concrete citation date of a citation. 
    title: CandidateCitation
    description: A candidate is a type of data that contains the basic data of candidate. In this case include date information. 
  PreferenceJobProfile:
    type: object
    properties:
      jobCode:
        type: string
        description: Job code of a concrete preference
      jobName:
        type: string
        description: Job name of a concrete preference
      priority:
        type: integer
        format: int32
        description: Priority of a concrete preference
    title: PreferenceJobProfile
