swagger: '2.0'
info:
  description: REST API Contact Data
  version: 1.0.0-SNAPSHOT
  title: Information about a candidate's contact data
host: 'localhost:8080'
basePath: /
tags:
  - name: Address
    description: Address related operations
  - name: Contact Profile
    description: |
      Operations related to several contact details at once
  - name: Email
    description: Operations related to email addresses
  - name: Messaging
    description: Operations related to messaging services
  - name: Telephone
    description: Operations related to telephone
  - name: Web
    description: Operations related to websites
paths:
  '/addresses/{id-candidate}':
    put:
      tags:
        - Address
      summary: Create or modify an address if it already exists
      operationId: upsertUsingPUT
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: listAddressResource
          description: listAddressResource
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/Address'
        - name: id-candidate
          in: path
          description: id-candidate
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '201':
          description: Created
        '400':
          description: BAD_REQUEST
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/contacts-profiles/{id-candidate}':
    get:
      tags:
        - Contact Profile
      summary: 'Search the contact details of a person: address, telephone and email.'
      description: Return a list and at this time the view will only return one item
      operationId: getUsingGET
      produces:
        - application/json
      parameters:
        - name: id-candidate
          in: path
          description: id-candidate
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ProfileContact'
        '204':
          description: NO_CONTENT
          schema:
            $ref: '#/definitions/ProfileContact'
        '400':
          description: BAD_REQUEST
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: NOT_FOUND
  '/emails/{id-candidate}':
    put:
      tags:
        - Email
      summary: Save or update email if that exist
      operationId: upsertUsingPUT_1
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: listEmailResource
          description: listEmailResource
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/Email'
        - name: id-candidate
          in: path
          description: id-candidate
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '201':
          description: Created
        '400':
          description: BAD_REQUEST
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/messagings/{id-candidate}':
    put:
      tags:
        - Messaging
      summary: Create or modify an address if it already exists
      operationId: upsertUsingPUT_2
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: listMessagingResource
          description: listMessagingResource
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/Messaging'
        - name: id-candidate
          in: path
          description: id-candidate
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '201':
          description: Created
        '400':
          description: BAD_REQUEST
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/telephones/{id-candidate}':
    put:
      tags:
        - Telephone
      summary: Create or modify a phone if it already exists
      operationId: upsertUsingPUT_3
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: listTelephoneResource
          description: listTelephoneResource
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/Telephone'
        - name: id-candidate
          in: path
          description: id-candidate
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '201':
          description: Created
        '400':
          description: BAD_REQUEST
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/webs/{id-candidate}':
    put:
      tags:
        - Web
      summary: Create or modify a website if it already exists
      operationId: upsertUsingPUT_4
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: listWebResource
          description: listWebResource
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/Web'
        - name: id-candidate
          in: path
          description: id-candidate
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '201':
          description: Created
        '400':
          description: BAD_REQUEST
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  Address:
    type: object
    properties:
      buildingNumber:
        type: string
        description: Number building

      cityName:
        type: string
        description: City name

      country:
        description: Country

        $ref: '#/definitions/Country'
      countryAreaType:
        description: Area type

        $ref: '#/definitions/CountryArea'
      idCandidate:
        type: string
        description: Contact ID

      preference:
        type: integer
        format: int32
        description: Order preference priority to be used as a contact

      streetName:
        type: string
        description: Name of street

      typeContact:
        type: string
        description: Contact type

      typeStreet:
        type: string
        description: Street type

      unit:
        type: string
        description: Unit

      useCode:
        type: string
        description: Use code

      zipCode:
        type: string
        description: Zip code

    title: Address
    description: Contact address of a person
  AdministrationDivision:
    type: object
    properties:
      area:
        type: string
        description: Area of administrative division

      level:
        description: Level of administrative division

        $ref: '#/definitions/LevelAdministrationDivision'
    title: AdministrationDivision
    description: Administrative division of country area
  AreaDialingCode:
    type: object
    properties:
      code:
        type: string
        description: Dialing code of the area of a country

      name:
        type: string
        description: Name of the marking area of a country

    title: AreaDialingCode
    description: Código del área de un país
  Country:
    type: object
    properties:
      code:
        type: string
        description: Country code

      name:
        type: string
        description: Country name

    title: Country
  CountryArea:
    type: object
    properties:
      code:
        type: string
        description: Area code of country

      name:
        type: string
        description: Area name of country

      typeArea:
        description: Administrative division of country area

        $ref: '#/definitions/AdministrationDivision'
    title: CountryArea
    description: Country area
  CountryDialing:
    type: object
    properties:
      code:
        type: integer
        format: int32
        description: Country Dialing Code

      name:
        type: string
        description: Country name

    title: CountryDialing
    description: Country Dialing Code
  Email:
    type: object
    properties:
      address:
        type: string
        description: Email address

      idCandidate:
        type: string
        description: Contact ID

      preference:
        type: integer
        format: int32
        description: Order preference priority to be used as a contact

      typeContact:
        type: string
        description: Contact type

      useCode:
        type: string
        description: Use code

    title: Email
  LevelAdministrationDivision:
    type: object
    properties:
      code:
        type: string
        description: Code of level administrative division

      name:
        type: string
        description: Name of level administrative division

    title: LevelAdministrationDivision
    description: Level administration division.
  Messaging:
    type: object
    properties:
      client:
        type: string
        description: Messaging client

      contact:
        type: string
        description: Messaging name

      idCandidate:
        type: string
        description: Contact ID

      preference:
        type: integer
        format: int32
        description: Order preference priority to be used as a contact

      typeContact:
        type: string
        description: Contact type

      useCode:
        type: string
        description: Use code

    title: Messaging
    description: Contact messaging
  ProfileContact:
    type: object
    properties:
      listAddress:
        type: array
        description: List of all the addresses of that candidate

        items:
          $ref: '#/definitions/ProfileContactAddress'
      listEmail:
        type: array
        description: List of all email addresses of that candidate

        items:
          $ref: '#/definitions/ProfileContactEmail'
      listTelephone:
        type: array
        description: List of all phone numbers of that candidate

        items:
          $ref: '#/definitions/ProfileContactTelephone'
    title: ProfileContact
    description: The profilecontact of a candidate is the most complete contact information possible of a candidate
  ProfileContactAddress:
    type: object
    properties:
      buildingNumber:
        type: string
        description: 'Number building '

      cityName:
        type: string
        description: City name of that address

      country:
        type: string
        description: Country of that address

      streetName:
        type: string
        description: Street name

      typeStreet:
        type: string
        description: Type street

      unit:
        type: string
        description: Unit

      zipCode:
        type: string
        description: Zip code of that address

    title: ProfileContactAddress
    description: Composition of most relevant address data
  ProfileContactEmail:
    type: object
    properties:
      address:
        type: string
        description: Address email

    title: ProfileContactEmail
    description: Composition of most relevant email data
  ProfileContactTelephone:
    type: object
    properties:
      access:
        type: string
        description: Access to that phone

      countryDialingCode:
        type: string
        description: Country code

      dialNumber:
        type: string
        description: Telephone number of candidate

      phoneExtension:
        type: string
        description: Phone extesion of a candidate

    title: ProfileContactTelephone
    description: Composition of most relevant telephone data
  ResponseEntity:
    type: object
    properties:
      body:
        type: object
      statusCode:
        type: string
        enum:
          - '100'
          - '101'
          - '102'
          - '103'
          - '200'
          - '201'
          - '202'
          - '203'
          - '204'
          - '205'
          - '206'
          - '207'
          - '208'
          - '226'
          - '300'
          - '301'
          - '302'
          - '303'
          - '304'
          - '305'
          - '307'
          - '308'
          - '400'
          - '401'
          - '402'
          - '403'
          - '404'
          - '405'
          - '406'
          - '407'
          - '408'
          - '409'
          - '410'
          - '411'
          - '412'
          - '413'
          - '414'
          - '415'
          - '416'
          - '417'
          - '418'
          - '419'
          - '420'
          - '421'
          - '422'
          - '423'
          - '424'
          - '426'
          - '428'
          - '429'
          - '431'
          - '451'
          - '500'
          - '501'
          - '502'
          - '503'
          - '504'
          - '505'
          - '506'
          - '507'
          - '508'
          - '509'
          - '510'
          - '511'
      statusCodeValue:
        type: integer
        format: int32
    title: ResponseEntity
  Telephone:
    type: object
    properties:
      access:
        type: string
      areaDialingCode:
        description: Código del área de la región

        $ref: '#/definitions/AreaDialingCode'
      countryDialingCode:
        description: Código del área del país

        $ref: '#/definitions/CountryDialing'
      dialNumber:
        type: string
        description: Número de marcación

      idCandidate:
        type: string
        description: Contact ID

      phoneExtension:
        type: string
        description: Extensión telefónica

      preference:
        type: integer
        format: int32
        description: Order preference priority to be used as a contact

      typeContact:
        type: string
        description: Contact type

      useCode:
        type: string
        description: Use code

    title: Telephone
    description: Teléfono de contacto
  Web:
    type: object
    properties:
      address:
        type: string
        description: Website address

      idCandidate:
        type: string
        description: Contact ID

      preference:
        type: integer
        format: int32
        description: Order preference priority to be used as a contact

      typeContact:
        type: string
        description: Contact type

      useCode:
        type: string
        description: Use code

    title: Web
    description: Web
