swagger: '2.0'
info:
  description: REST API Labor preference
  version: 1.0.0-SNAPSHOT
  title: Information about a candidate's labor preference
host: 'localhost:8080'
basePath: /
tags:
  - name: Labor Preference
    description: Operations related to labor preference
  - name: Labor Preference Profile
    description: Operations related to labor preference profile
paths:
  '/labor-preferences-profiles/{id-candidate}':
    get:
      tags:
        - Labor Preference Profile
      summary: Look for the labor preferences (demand sometimes called) of a candidate; they are divided into the general preference and the jobs that I want
      description: A default preference is returned and also a specific preference is associated with each job
      operationId: getUsingGET
      produces:
        - application/json
      parameters:
        - name: id-candidate
          in: path
          description: id-candidate
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/LaborPreferenceProfile'
        '400':
          description: BAD_REQUEST
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: NOT_FOUND
  '/labor-preferences/{id-candidate}':
    put:
      tags:
        - Labor Preference
      summary: Create or modify a candidate's work preference
      operationId: upsertUsingPUT
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: laborPreferenceResource
          description: laborPreferenceResource
          required: true
          schema:
            $ref: '#/definitions/LaborPreference'
        - name: id-candidate
          in: path
          description: id-candidate
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '201':
          description: Created
        '400':
          description: BAD_REQUEST
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  Availability:
    type: object
    properties:
      endDate:
        type: string
        format: date-time
        description: End date of a availability

      immediateAvailability:
        type: boolean
        example: false
        description: Indicator of inmediate availability of a candidate

      startDate:
        type: string
        format: date-time
        description: Start date of a availability

    title: Availability
  AvailabilityProfile:
    type: object
    properties:
      endDate:
        type: string
        format: date-time
        description: End date of a availability

      immediateAvailability:
        type: boolean
        example: false
        description: Indicator of a inmediate availability

      startDate:
        type: string
        format: date-time
        description: Start date of a availability

    title: AvailabilityProfile
  ContractType:
    type: object
    properties:
      code:
        type: string
        description: Code of a contract type

      name:
        type: string
        description: Name of contract type

    title: ContractType
  EmploymentPreference:
    type: object
    properties:
      favoriteOrganizationType:
        type: array
        description: List of organization type

        items:
          $ref: '#/definitions/Organization'
      maxEmployments:
        type: string
        description: Max employments

      minEmployments:
        type: string
        description: Min employments

      preferredIndustries:
        type: array
        description: List of prefered industries

        items:
          $ref: '#/definitions/IndustryType'
    title: EmploymentPreference
  IndustryType:
    type: object
    properties:
      code:
        type: string
        description: Code of industry type

      name:
        type: string
        description: Name of industry type

    title: IndustryType
  JobCategory:
    type: object
    properties:
      code:
        type: string
        description: Job category code

      name:
        type: string
        description: Job category name

    title: JobCategory
  JobPreference:
    type: object
    properties:
      defaultPreference:
        description: Default preference

        $ref: '#/definitions/Preference'
      jobCategory:
        description: Job category of a job preference

        $ref: '#/definitions/JobCategory'
      priority:
        type: integer
        format: int32
        description: Priority of a concrete preference

    title: JobPreference
  LaborPreference:
    type: object
    properties:
      availability:
        description: Availability of a candidate

        $ref: '#/definitions/Availability'
      defaultPreference:
        description: Default preference of a candidate

        $ref: '#/definitions/Preference'
      jobPreferences:
        type: array
        description: List of all preferences jobs of a candidate

        items:
          $ref: '#/definitions/JobPreference'
    title: LaborPreference
    description: Labor preference of a candidate
  LaborPreferenceProfile:
    type: object
    properties:
      availability:
        description: Availability of a candidate

        $ref: '#/definitions/AvailabilityProfile'
      defaultPreference:
        description: Default preference of a candidate

        $ref: '#/definitions/PreferenceProfile'
      idCandidate:
        type: string
        description: ID of a candidate

      preferenceJob:
        type: array
        description: List of all preferences jobs of a candidate

        items:
          $ref: '#/definitions/PreferenceJobProfile'
    title: LaborPreferenceProfile
    description: Labor preference of a candidate
  Location:
    type: object
    properties:
      maxDistance:
        type: integer
        format: int32
        description: Max distance of location

      referenceLocation:
        description: Reference location

        $ref: '#/definitions/ReferenceLocation'
      unitType:
        description: Unit type of a location

        $ref: '#/definitions/UnitType'
    title: Location
  LocationProfile:
    type: object
    properties:
      city:
        type: string
        description: City reference of a location

      country:
        type: string
        description: Country reference of a location

      maxDistance:
        type: integer
        format: int32
        description: Max distance of a location

      unitType:
        type: string
        description: Unit of distance

    title: LocationProfile
  MonetaryType:
    type: object
    properties:
      code:
        type: string
        description: Code of monetary type

      name:
        type: string
        description: Name of monetary type

    title: MonetaryType
  Organization:
    type: object
    properties:
      code:
        type: string
        description: Code of organization type

      name:
        type: string
        description: Name of organization type

    title: Organization
  Preference:
    type: object
    properties:
      contractType:
        description: Contract type of a concrete candidate's preference

        $ref: '#/definitions/ContractType'
      employmentPreference:
        description: Employment preference

        $ref: '#/definitions/EmploymentPreference'
      location:
        description: Location of a concrete candidate's preference

        $ref: '#/definitions/Location'
      relocation:
        description: Relocation preference of a concrete candidate's preference

        $ref: '#/definitions/Relocation'
      remuneration:
        description: Remuneration of a concrete candidate's preference

        $ref: '#/definitions/Remuneration'
      willingTravel:
        description: Willing travel of a concrete candidate's preference

        $ref: '#/definitions/WillingTravel'
    title: Preference
  PreferenceJobProfile:
    type: object
    properties:
      jobCode:
        type: string
        description: Job code of a concrete preference

      jobName:
        type: string
        description: Job name of a concrete preference

      priority:
        type: integer
        format: int32
        description: Priority of a concrete preference

    title: PreferenceJobProfile
  PreferenceProfile:
    type: object
    properties:
      contactType:
        type: string
        description: Contract type of a candidate

      location:
        description: Location preffered of a candidate

        $ref: '#/definitions/LocationProfile'
      remuneration:
        description: Remuneration preffered of a candidate

        $ref: '#/definitions/RemunerationProfile'
    title: PreferenceProfile
    description: Preference of a candidate
  ReferenceLocation:
    type: object
    properties:
      city:
        type: string
        description: Name of a city of reference location

      country:
        type: string
        description: Name of a country of reference location

    title: ReferenceLocation
  Relocation:
    type: object
    properties:
      description:
        type: string
        description: Information more especific about relocation

      relocationWilling:
        type: boolean
        example: false
        description: Willing of relocation

    title: Relocation
  Remuneration:
    type: object
    properties:
      maxRemuneration:
        type: integer
        format: int32
        description: Max remuneration

      minRemuneration:
        type: integer
        format: int32
        description: Min remuneration

      monetaryType:
        description: Monetary type

        $ref: '#/definitions/MonetaryType'
      typeRemuneration:
        description: Type remuneration

        $ref: '#/definitions/RemunerationType'
      unitRemuneration:
        description: Unit remuneration type

        $ref: '#/definitions/UnitRemunerationType'
    title: Remuneration
  RemunerationProfile:
    type: object
    properties:
      maxRemuneration:
        type: integer
        format: int32
        description: Max remuneration

      minRemuneration:
        type: integer
        format: int32
        description: Min remuneration

      monetaryType:
        type: string
        description: Monetary type of a remuneration

      unitType:
        type: string
        description: Unit type of a remuneration

    title: RemunerationProfile
  RemunerationType:
    type: object
    properties:
      code:
        type: string
        description: Code of remuneration type

      name:
        type: string
        description: Name of remuneration type

    title: RemunerationType
  ResponseEntity:
    type: object
    properties:
      body:
        type: object
      statusCode:
        type: string
        enum:
          - '100'
          - '101'
          - '102'
          - '103'
          - '200'
          - '201'
          - '202'
          - '203'
          - '204'
          - '205'
          - '206'
          - '207'
          - '208'
          - '226'
          - '300'
          - '301'
          - '302'
          - '303'
          - '304'
          - '305'
          - '307'
          - '308'
          - '400'
          - '401'
          - '402'
          - '403'
          - '404'
          - '405'
          - '406'
          - '407'
          - '408'
          - '409'
          - '410'
          - '411'
          - '412'
          - '413'
          - '414'
          - '415'
          - '416'
          - '417'
          - '418'
          - '419'
          - '420'
          - '421'
          - '422'
          - '423'
          - '424'
          - '426'
          - '428'
          - '429'
          - '431'
          - '451'
          - '500'
          - '501'
          - '502'
          - '503'
          - '504'
          - '505'
          - '506'
          - '507'
          - '508'
          - '509'
          - '510'
          - '511'
      statusCodeValue:
        type: integer
        format: int32
    title: ResponseEntity
  UnitRemunerationType:
    type: object
    properties:
      code:
        type: string
        description: Code of unit type

      name:
        type: string
        description: Name of unit type

    title: UnitRemunerationType
  UnitType:
    type: object
    properties:
      code:
        type: string
        description: Code of unit type

      name:
        type: string
        description: Name of unit type

    title: UnitType
  WillingTravel:
    type: object
    properties:
      percentageTime:
        type: integer
        format: int32
        description: Time percentage of willing travel

      travelWilling:
        type: boolean
        example: false
        description: Travel willing of a concrete candidate's preference

    title: WillingTravel
